import type { UserProfile } from '@/features/app-shell/types';

export const DEMO_USERS: Record<string, UserProfile> = {
  'secureadmin@siliconeconnect.com': {
    id: 'super-admin-1',
    email: 'secureadmin@siliconeconnect.com',
    name: 'Admin',
    firstName: 'Admin',
    lastName: 'SC',
    username: 'Admin',
    passwordHash: '@Adminsc2026@',
    role: 'SUPER_ADMIN',
    isActive: true,
    isBlocked: false,
    isFirstLogin: true,
    mustChangePassword: true,
    failedLoginAttempts: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  'theresia@siliconeconnect.com': {
    id: 'sup-1',
    email: 'theresia@siliconeconnect.com',
    name: 'Theresia',
    firstName: 'Theresia',
    lastName: '',
    username: 'Theresia',
    passwordHash: '#Esia2026RepSC',
    role: 'RESPONSABLE',
    isActive: true,
    isBlocked: false,
    isFirstLogin: true,
    mustChangePassword: true,
    failedLoginAttempts: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  'kevine@siliconeconnect.com': {
    id: 'agent-c4',
    email: 'kevine@siliconeconnect.com',
    name: 'Kevine',
    firstName: 'Kevine',
    lastName: '',
    username: 'Kevine',
    passwordHash: '@Admin2026SC',
    role: 'TECHNICIEN_NO',
    shiftId: 'shift-c',
    shift: { id: 'shift-c', name: 'C', color: 'green', colorCode: '#22C55E' },
    responsibility: 'MONITORING',
    isActive: true,
    isBlocked: false,
    isFirstLogin: true,
    mustChangePassword: true,
    failedLoginAttempts: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  'audrey@siliconeconnect.com': {
    id: 'agent-c1',
    email: 'audrey@siliconeconnect.com',
    name: 'Audrey',
    firstName: 'Audrey',
    lastName: '',
    username: 'Audrey',
    passwordHash: '@Tech2026NOCSC',
    role: 'TECHNICIEN_NO',
    shiftId: 'shift-c',
    shift: { id: 'shift-c', name: 'C', color: 'green', colorCode: '#22C55E' },
    responsibility: 'CALL_CENTER',
    isActive: true,
    isBlocked: false,
    isFirstLogin: true,
    mustChangePassword: true,
    failedLoginAttempts: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  'lotti@siliconeconnect.com': {
    id: 'agent-c3',
    email: 'lotti@siliconeconnect.com',
    name: 'Lotti',
    firstName: 'Lotti',
    lastName: '',
    username: 'Lotti',
    passwordHash: '@Lotty*SC2026',
    role: 'TECHNICIEN_NO',
    shiftId: 'shift-c',
    shift: { id: 'shift-c', name: 'C', color: 'green', colorCode: '#22C55E' },
    responsibility: 'REPORTING_1',
    isActive: true,
    isBlocked: false,
    isFirstLogin: true,
    mustChangePassword: true,
    failedLoginAttempts: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  'lapreuve@siliconeconnect.com': {
    id: 'agent-c2',
    email: 'lapreuve@siliconeconnect.com',
    name: 'Lapreuve',
    firstName: 'Lapreuve',
    lastName: '',
    username: 'Lapreuve',
    passwordHash: 'SC2026@LapNOC!',
    role: 'TECHNICIEN_NO',
    shiftId: 'shift-c',
    shift: { id: 'shift-c', name: 'C', color: 'green', colorCode: '#22C55E' },
    responsibility: 'REPORTING_2',
    isActive: true,
    isBlocked: false,
    isFirstLogin: true,
    mustChangePassword: true,
    failedLoginAttempts: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  'luca@siliconeconnect.com': {
    id: 'agent-a3',
    email: 'luca@siliconeconnect.com',
    name: 'Luca',
    firstName: 'Luca',
    lastName: '',
    username: 'Luca',
    passwordHash: 'Lulu_SC#2026',
    role: 'TECHNICIEN_NO',
    shiftId: 'shift-a',
    shift: { id: 'shift-a', name: 'A', color: 'blue', colorCode: '#3B82F6' },
    responsibility: 'REPORTING_1',
    isActive: true,
    isBlocked: false,
    isFirstLogin: true,
    mustChangePassword: true,
    failedLoginAttempts: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  'jose@siliconeconnect.com': {
    id: 'agent-a4',
    email: 'jose@siliconeconnect.com',
    name: 'José',
    firstName: 'José',
    lastName: '',
    username: 'José',
    passwordHash: 'J0se!2026_SC',
    role: 'TECHNICIEN_NO',
    shiftId: 'shift-a',
    shift: { id: 'shift-a', name: 'A', color: 'blue', colorCode: '#3B82F6' },
    responsibility: 'REPORTING_2',
    isActive: true,
    isBlocked: false,
    isFirstLogin: true,
    mustChangePassword: true,
    failedLoginAttempts: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  'casimir@siliconeconnect.com': {
    id: 'agent-a2',
    email: 'casimir@siliconeconnect.com',
    name: 'Casimir',
    firstName: 'Casimir',
    lastName: '',
    username: 'Casimir',
    passwordHash: 'Cas_SC2026$mir',
    role: 'TECHNICIEN_NO',
    shiftId: 'shift-a',
    shift: { id: 'shift-a', name: 'A', color: 'blue', colorCode: '#3B82F6' },
    responsibility: 'MONITORING',
    isActive: true,
    isBlocked: false,
    isFirstLogin: true,
    mustChangePassword: true,
    failedLoginAttempts: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  'alaine@siliconeconnect.com': {
    id: 'agent-a1',
    email: 'alaine@siliconeconnect.com',
    name: 'Alaine',
    firstName: 'Alaine',
    lastName: '',
    username: 'Alaine',
    passwordHash: 'Ala!2026_NOC',
    role: 'TECHNICIEN_NO',
    shiftId: 'shift-a',
    shift: { id: 'shift-a', name: 'A', color: 'blue', colorCode: '#3B82F6' },
    responsibility: 'CALL_CENTER',
    isActive: true,
    isBlocked: false,
    isFirstLogin: true,
    mustChangePassword: true,
    failedLoginAttempts: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  'furys@siliconeconnect.com': {
    id: 'agent-b4',
    email: 'furys@siliconeconnect.com',
    name: 'Furys',
    firstName: 'Furys',
    lastName: '',
    username: 'Furys',
    passwordHash: 'Fury2026@SC#',
    role: 'TECHNICIEN_NO',
    shiftId: 'shift-b',
    shift: { id: 'shift-b', name: 'B', color: 'yellow', colorCode: '#EAB308' },
    responsibility: 'REPORTING_2',
    isActive: true,
    isBlocked: false,
    isFirstLogin: true,
    mustChangePassword: true,
    failedLoginAttempts: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  'marly@siliconeconnect.com': {
    id: 'agent-b3',
    email: 'marly@siliconeconnect.com',
    name: 'Marly',
    firstName: 'Marly',
    lastName: '',
    username: 'Marly',
    passwordHash: 'Marly_SC2026!',
    role: 'TECHNICIEN_NO',
    shiftId: 'shift-b',
    shift: { id: 'shift-b', name: 'B', color: 'yellow', colorCode: '#EAB308' },
    responsibility: 'REPORTING_1',
    isActive: true,
    isBlocked: false,
    isFirstLogin: true,
    mustChangePassword: true,
    failedLoginAttempts: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  'sahra@siliconeconnect.com': {
    id: 'agent-b1',
    email: 'sahra@siliconeconnect.com',
    name: 'Sahra',
    firstName: 'Sahra',
    lastName: '',
    username: 'Sahra',
    passwordHash: 'Sahra2026*SC',
    role: 'TECHNICIEN_NO',
    shiftId: 'shift-b',
    shift: { id: 'shift-b', name: 'B', color: 'yellow', colorCode: '#EAB308' },
    responsibility: 'CALL_CENTER',
    isActive: true,
    isBlocked: false,
    isFirstLogin: true,
    mustChangePassword: true,
    failedLoginAttempts: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  'severin@siliconeconnect.com': {
    id: 'agent-b2',
    email: 'severin@siliconeconnect.com',
    name: 'Severin',
    firstName: 'Severin',
    lastName: '',
    username: 'Severin',
    passwordHash: 'Sev2026_SC@rin',
    role: 'TECHNICIEN_NO',
    shiftId: 'shift-b',
    shift: { id: 'shift-b', name: 'B', color: 'yellow', colorCode: '#EAB308' },
    responsibility: 'MONITORING',
    isActive: true,
    isBlocked: false,
    isFirstLogin: true,
    mustChangePassword: true,
    failedLoginAttempts: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  'lyse@siliconeconnect.com': {
    id: 'agent-lyse',
    email: 'lyse@siliconeconnect.com',
    name: 'Lyse',
    firstName: 'Lyse',
    lastName: '',
    username: 'Lyse',
    passwordHash: 'Lyse_SC!2026',
    role: 'TECHNICIEN_NO',
    isActive: true,
    isBlocked: false,
    isFirstLogin: true,
    mustChangePassword: true,
    failedLoginAttempts: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
};
