import type { ActivityLog, NotificationItem, Task } from '@/features/app-shell/core/shared/types';

export function buildInitialTasks(nowMs = Date.now()): Task[] {
  return [
    {
      id: 't1',
      userId: 'agent-a1',
      userName: 'Alaine',
      title: 'Verifier alarmes Zabbix',
      description: 'Monitoring alerts',
      status: 'in_progress',
      category: 'surveillance',
      priority: 'medium',
      startTime: new Date(nowMs),
      estimatedEndTime: new Date(nowMs + 60 * 60 * 1000),
      estimatedDuration: 60,
      comments: [],
      alerts: [],
      history: [],
      tags: [],
      isOverdue: false,
      isNotified: false,
      createdAt: new Date(nowMs),
      updatedAt: new Date(nowMs),
    },
    {
      id: 't2',
      userId: 'agent-a1',
      userName: 'Alaine',
      title: 'Envoyer graphes 09h',
      description: 'Graphes trafic',
      status: 'completed',
      category: 'administrative',
      priority: 'low',
      startTime: new Date(nowMs - 90 * 60 * 1000),
      estimatedEndTime: new Date(nowMs - 30 * 60 * 1000),
      estimatedDuration: 60,
      actualEndTime: new Date(nowMs),
      actualDuration: 60,
      comments: [],
      alerts: [],
      history: [],
      tags: [],
      isOverdue: false,
      isNotified: true,
      createdAt: new Date(nowMs),
      updatedAt: new Date(nowMs),
      completedAt: new Date(nowMs),
    },
    {
      id: 't3',
      userId: 'agent-c4',
      userName: 'Kevine',
      title: 'Appel client ACME',
      description: 'Suivi incident',
      status: 'pending',
      category: 'incident',
      priority: 'high',
      startTime: new Date(nowMs),
      estimatedEndTime: new Date(nowMs + 45 * 60 * 1000),
      estimatedDuration: 45,
      comments: [],
      alerts: [],
      history: [],
      tags: [],
      isOverdue: false,
      isNotified: false,
      createdAt: new Date(nowMs),
      updatedAt: new Date(nowMs),
    },
    {
      id: 't4',
      userId: 'agent-c1',
      userName: 'Audrey',
      title: 'Escalade lien principal client MTT',
      description: 'Coordonner l escalade avec l operateur backbone et suivre le retour terrain.',
      status: 'in_progress',
      category: 'incident',
      priority: 'critical',
      startTime: new Date(nowMs - 3 * 60 * 60 * 1000),
      estimatedEndTime: new Date(nowMs + 2 * 60 * 60 * 1000),
      estimatedDuration: 300,
      comments: [],
      alerts: [],
      history: [],
      tags: ['phase:gestion incidents', 'client:mtt', 'milestone:escalade'],
      isOverdue: false,
      isNotified: false,
      createdAt: new Date(nowMs - 3 * 60 * 60 * 1000),
      updatedAt: new Date(nowMs),
    },
    {
      id: 't5',
      userId: 'agent-a3',
      userName: 'Theresia',
      title: 'Maintenance preventive coeur Mikrotik NOC',
      description: 'Verifier la redondance, exporter la configuration et planifier le rollback.',
      status: 'pending',
      category: 'maintenance',
      priority: 'high',
      startTime: new Date(nowMs + 24 * 60 * 60 * 1000),
      estimatedEndTime: new Date(nowMs + 26 * 60 * 60 * 1000),
      estimatedDuration: 120,
      comments: [],
      alerts: [],
      history: [],
      tags: ['phase:maintenance plateforme', 'change_window'],
      isOverdue: false,
      isNotified: false,
      createdAt: new Date(nowMs),
      updatedAt: new Date(nowMs),
    },
    {
      id: 't6',
      userId: 'agent-b2',
      userName: 'Wivine MITSOMOY',
      title: 'Deploiement dashboard SLA Grafana',
      description: 'Publier le tableau de bord SLA et verifier les seuils d alertes clients VIP.',
      status: 'pending',
      category: 'surveillance',
      priority: 'medium',
      startTime: new Date(nowMs + 2 * 24 * 60 * 60 * 1000),
      estimatedEndTime: new Date(nowMs + 5 * 24 * 60 * 60 * 1000),
      estimatedDuration: 240,
      comments: [],
      alerts: [],
      history: [],
      tags: ['phase:supervision proactive', 'grafana', 'reporting'],
      isOverdue: false,
      isNotified: false,
      createdAt: new Date(nowMs),
      updatedAt: new Date(nowMs),
    },
    {
      id: 't7',
      userId: 'agent-c4',
      userName: 'Kevine',
      title: 'Validation planning astreinte semaine prochaine',
      description: 'Consolider les shifts, les repos individuels et le backup call center.',
      status: 'pending',
      category: 'administrative',
      priority: 'medium',
      startTime: new Date(nowMs + 3 * 24 * 60 * 60 * 1000),
      estimatedEndTime: new Date(nowMs + 3 * 24 * 60 * 60 * 1000 + 90 * 60 * 1000),
      estimatedDuration: 90,
      comments: [],
      alerts: [],
      history: [],
      tags: ['phase:gouvernance', 'planning'],
      isOverdue: false,
      isNotified: false,
      createdAt: new Date(nowMs),
      updatedAt: new Date(nowMs),
    },
    {
      id: 't8',
      userId: 'agent-a1',
      userName: 'Alaine',
      title: 'Recette procedure bascule fibre secours',
      description: 'Tester le scenario de bascule et documenter le runbook de reprise.',
      status: 'pending',
      category: 'other',
      priority: 'high',
      startTime: new Date(nowMs + 6 * 24 * 60 * 60 * 1000),
      estimatedEndTime: new Date(nowMs + 8 * 24 * 60 * 60 * 1000),
      estimatedDuration: 180,
      comments: [],
      alerts: [],
      history: [],
      tags: ['phase:pilotage livraison', 'recette'],
      isOverdue: false,
      isNotified: false,
      createdAt: new Date(nowMs),
      updatedAt: new Date(nowMs),
    },
  ];
}

export function buildInitialActivities(): ActivityLog[] {
  return [];
}

export function buildDefaultNotifications(nowMs = Date.now()): NotificationItem[] {
  return [
    {
      id: '1',
      message: 'Incident critique detecte',
      type: 'warning',
      read: false,
      createdAt: new Date(nowMs),
    },
    {
      id: '2',
      message: 'Nouveau ticket assigne',
      type: 'info',
      read: false,
      createdAt: new Date(nowMs),
    },
    {
      id: '3',
      message: 'Handover valide',
      type: 'success',
      read: true,
      createdAt: new Date(nowMs),
    },
  ];
}