'use client';

import { AppAdminUserDialogsSection } from '@/features/app-shell/components/admin/AppAdminUserDialogsSection';
import { AppAvatarViewerDialog } from '@/features/app-shell/components/dialogs/AppAvatarViewerDialog';
import { AppProfileSettingsDialogsSection } from '@/features/app-shell/components/dialogs/AppProfileSettingsDialogsSection';

type AppShellDialogsSectionProps = any;

export function AppShellDialogsSection(props: AppShellDialogsSectionProps) {
  const {
    chatAvatarInputRef,
    handleConversationAvatarUpload,
    restDialogOpen,
    setRestDialogOpen,
    user,
    userRestInfo,
    profileDialogOpen,
    setProfileDialogOpen,
    openAvatarViewer,
    avatarFileInputRef,
    handleAvatarUpload,
    persistUserProfile,
    fetchConversations,
    editProfileDialogOpen,
    setEditProfileDialogOpen,
    editFirstName,
    setEditFirstName,
    editLastName,
    setEditLastName,
    editEmail,
    setEditEmail,
    editUsername,
    setEditUsername,
    handleSaveProfile,
    securityDialogOpen,
    setSecurityDialogOpen,
    setSelectedUser,
    setEditPassword,
    setConfirmPassword,
    isAdminPasswordResetMode,
    selectedUser,
    editPassword,
    confirmPassword,
    validatePassword,
    handleSaveSecurity,
    shiftDialogOpen,
    setShiftDialogOpen,
    editShift,
    setEditShift,
    editResponsibility,
    setEditResponsibility,
    handleSaveShift,
    settingsDialogOpen,
    setSettingsDialogOpen,
    theme,
    setTheme,
    isSuperAdmin,
    usersManagementOpen,
    setUsersManagementOpen,
    userSearchQuery,
    setUserSearchQuery,
    roleFilter,
    setRoleFilter,
    setCreateUserDialogOpen,
    filteredUsers,
    ROLE_CONFIG,
    handleChangeUserRole,
    handleToggleBlockUser,
    handleDeleteUser,
    canManageUsers,
    createUserDialogOpen,
    editRole,
    setEditRole,
    handleCreateUser,
    usersActionInProgress,
    editUserDialogOpen,
    setEditUserDialogOpen,
    editUserIsActive,
    setEditUserIsActive,
    editUserIsBlocked,
    setEditUserIsBlocked,
    handleUpdateUserDetails,
    userToEdit,
    deleteConfirmationOpen,
    setDeleteConfirmationOpen,
    setUserToDelete,
    setDeleteConfirmationInput,
    userToDelete,
    deleteConfirmationInput,
    confirmDeleteUser,
    auditLogDialogOpen,
    setAuditLogDialogOpen,
    refreshAuditLog,
    auditLogRefreshing,
    auditLogDateFrom,
    setAuditLogDateFrom,
    auditLogDateTo,
    setAuditLogDateTo,
    auditLogActionType,
    setAuditLogActionType,
    uniqueActionTypes,
    auditLogStatusFilter,
    setAuditLogStatusFilter,
    auditLogUserFilter,
    setAuditLogUserFilter,
    filteredAuditLogs,
    auditLogs,
    avatarViewerOpen,
    setAvatarViewerOpen,
    avatarViewerData,
  } = props;

  return (
    <>
      <input
        ref={chatAvatarInputRef}
        type="file"
        accept="image/*"
        className="hidden"
        onChange={handleConversationAvatarUpload}
      />

      <AppProfileSettingsDialogsSection
        restDialogOpen={restDialogOpen}
        setRestDialogOpen={setRestDialogOpen}
        user={user}
        userRestInfo={userRestInfo}
        profileDialogOpen={profileDialogOpen}
        setProfileDialogOpen={setProfileDialogOpen}
        openAvatarViewer={openAvatarViewer}
        avatarFileInputRef={avatarFileInputRef}
        handleAvatarUpload={handleAvatarUpload}
        persistUserProfile={persistUserProfile}
        fetchConversations={fetchConversations}
        editProfileDialogOpen={editProfileDialogOpen}
        setEditProfileDialogOpen={setEditProfileDialogOpen}
        editFirstName={editFirstName}
        setEditFirstName={setEditFirstName}
        editLastName={editLastName}
        setEditLastName={setEditLastName}
        editEmail={editEmail}
        setEditEmail={setEditEmail}
        editUsername={editUsername}
        setEditUsername={setEditUsername}
        handleSaveProfile={handleSaveProfile}
        securityDialogOpen={securityDialogOpen}
        setSecurityDialogOpen={setSecurityDialogOpen}
        setSelectedUser={setSelectedUser}
        setEditPassword={setEditPassword}
        setConfirmPassword={setConfirmPassword}
        isAdminPasswordResetMode={isAdminPasswordResetMode}
        selectedUser={selectedUser}
        editPassword={editPassword}
        confirmPassword={confirmPassword}
        validatePassword={validatePassword}
        handleSaveSecurity={handleSaveSecurity}
        shiftDialogOpen={shiftDialogOpen}
        setShiftDialogOpen={setShiftDialogOpen}
        editShift={editShift}
        setEditShift={setEditShift}
        editResponsibility={editResponsibility}
        setEditResponsibility={setEditResponsibility}
        handleSaveShift={handleSaveShift}
        settingsDialogOpen={settingsDialogOpen}
        setSettingsDialogOpen={setSettingsDialogOpen}
        theme={theme || 'light'}
        setTheme={setTheme}
      />

      <AppAdminUserDialogsSection
        isSuperAdmin={isSuperAdmin}
        user={user}
        usersManagementOpen={usersManagementOpen}
        setUsersManagementOpen={setUsersManagementOpen}
        userSearchQuery={userSearchQuery}
        setUserSearchQuery={setUserSearchQuery}
        roleFilter={roleFilter}
        setRoleFilter={setRoleFilter}
        setCreateUserDialogOpen={setCreateUserDialogOpen}
        filteredUsers={filteredUsers}
        ROLE_CONFIG={ROLE_CONFIG}
        handleChangeUserRole={handleChangeUserRole}
        handleToggleBlockUser={handleToggleBlockUser}
        setSelectedUser={setSelectedUser}
        setEditPassword={setEditPassword}
        setConfirmPassword={setConfirmPassword}
        setSecurityDialogOpen={setSecurityDialogOpen}
        handleDeleteUser={handleDeleteUser}
        canManageUsers={canManageUsers}
        createUserDialogOpen={createUserDialogOpen}
        editFirstName={editFirstName}
        setEditFirstName={setEditFirstName}
        editLastName={editLastName}
        setEditLastName={setEditLastName}
        editEmail={editEmail}
        setEditEmail={setEditEmail}
        editUsername={editUsername}
        setEditUsername={setEditUsername}
        editRole={editRole}
        setEditRole={setEditRole}
        editShift={editShift}
        setEditShift={setEditShift}
        editResponsibility={editResponsibility}
        setEditResponsibility={setEditResponsibility}
        editPassword={editPassword}
        handleCreateUser={handleCreateUser}
        usersActionInProgress={usersActionInProgress}
        editUserDialogOpen={editUserDialogOpen}
        setEditUserDialogOpen={setEditUserDialogOpen}
        editUserIsActive={editUserIsActive}
        setEditUserIsActive={setEditUserIsActive}
        editUserIsBlocked={editUserIsBlocked}
        setEditUserIsBlocked={setEditUserIsBlocked}
        handleUpdateUserDetails={handleUpdateUserDetails}
        userToEdit={userToEdit}
        deleteConfirmationOpen={deleteConfirmationOpen}
        setDeleteConfirmationOpen={setDeleteConfirmationOpen}
        setUserToDelete={setUserToDelete}
        setDeleteConfirmationInput={setDeleteConfirmationInput}
        userToDelete={userToDelete}
        deleteConfirmationInput={deleteConfirmationInput}
        confirmDeleteUser={confirmDeleteUser}
        auditLogDialogOpen={auditLogDialogOpen}
        setAuditLogDialogOpen={setAuditLogDialogOpen}
        refreshAuditLog={refreshAuditLog}
        auditLogRefreshing={auditLogRefreshing}
        auditLogDateFrom={auditLogDateFrom}
        setAuditLogDateFrom={setAuditLogDateFrom}
        auditLogDateTo={auditLogDateTo}
        setAuditLogDateTo={setAuditLogDateTo}
        auditLogActionType={auditLogActionType}
        setAuditLogActionType={setAuditLogActionType}
        uniqueActionTypes={uniqueActionTypes}
        auditLogStatusFilter={auditLogStatusFilter}
        setAuditLogStatusFilter={setAuditLogStatusFilter}
        auditLogUserFilter={auditLogUserFilter}
        setAuditLogUserFilter={setAuditLogUserFilter}
        filteredAuditLogs={filteredAuditLogs}
        auditLogs={auditLogs}
      />

      <AppAvatarViewerDialog
        open={avatarViewerOpen}
        onOpenChange={setAvatarViewerOpen}
        data={avatarViewerData}
      />
    </>
  );
}